#!/bin/bash

sudo apt install python-mysql.connector -y 

cd /home/pi/ &&
git clone https://github.com/laulausen/mirrohr.git &&

sudo cp -r /home/pi/mirrohr/files/etc/default/.musterloesungen /etc/default/ &&

sudo sh -c 'echo "CREATE SCHEMA DBName;" | mysql -u root' 
sudo sh -c 'echo "CREATE USER \"benutzer\"@\"localhost\" IDENTIFIED BY \"password\";" | mysql -u root'
sudo sh -c 'echo "GRANT ALL PRIVILEGES ON DBName.* TO \"benutzer\"@\"localhost\";" | mysql -u root' 
sudo sh -c 'echo "FLUSH PRIVILEGES;" | mysql -u root'
sudo sh -c 'echo "CREATE TABLE DBName.Flags(name VARCHAR(45) NOT NULL, wert INT NOT NULL, PRIMARY KEY (name));" | mysql -u root' 
sudo sh -c 'echo "INSERT INTO DBName.Flags (name,wert) VALUES (\"bewegung\", 0);" | mysql -u root' 
 
sudo cp /etc/default/.musterloesungen/getState.php /var/www/html/modules/info/frontend/
sudo cp /etc/default/.musterloesungen/script.js /var/www/html/modules/info/frontend/
sudo sed -i "s|exit 0||g" /etc/rc.local
sudo sh -c 'echo "/usr/bin/python /etc/default/.musterloesungen/clap_count_with_db.py &" >> /etc/rc.local'
sudo sh -c 'echo "/usr/bin/python /etc/default/.musterloesungen/movement_detection_with_db.py &" >> /etc/rc.local'
sudo sh -c 'echo "exit 0" >> /etc/rc.local'
sleep 2
read -p "Geben Sie den GPIO-PIN (bcm) fuer den Bewegungssensor an: " pin_move &&
read -p "Geben Sie den GPIO-PIN (bcm) fuer den Soundsensor an: " pin_sound &&

sudo sed -i "s|PIN = 26|PIN = $pin_move|g" /etc/default/.musterloesungen/movement_detection_with_db.py
sudo sed -i "s|PIN = 26|PIN = $pin_sound|g" /etc/default/.musterloesungen/clap_count_with_db.py
