#!/bin/sh
#sudo apt update
sudo apt install -y php php-bz2 php-curl php-gd php-intl php-mysql php-soap php-xml php-zip php-cli-prompt php-composer-ca-bundle php-composer-semver php-composer-spdx-licenses php-json-schema php-symfony-console php-symfony-filesystem php-symfony-finder php-symfony-polyfill-mbstring php-symfony-process mariadb-server chromium-browser xinit matchbox qrencode hostapd dnsmasq fbi geoclue-2.0 xserver-xorg-video-fbdev xserver-xorg-video-fbturbo xterm libgles2 libgles2-mesa-dev libraspberrypi-dev libraspberrypi0 libraspberrypi-bin pwgen gldriver-test &&
#sudo cp /home/pi/mirrohr/rc.make-a-mirrohr /etc/rc.local &&
sudo reboot
