#!/bin/bash

# script for making a mirrohr

sudo systemctl stop apache2.service

sudo rm -r /var/www/html/*
sudo cp /home/pi/mirrohr/html.tar /var/www/html/
cd /var/www/html/
sudo tar -xpf html.tar
sudo rm /var/www/html/html.tar
cd /home/pi/mirrohr/
sudo ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load

sudo cp -r /home/pi/mirrohr/locales/* /etc/
sudo locale-gen
sudo update-locale de_DE.UTF-8
sudo timedatectl set-timezone Europe/Berlin

sudo mysql -u root < /home/pi/mirrohr/mirrohr.sql
sudo mysql_upgrade --force


sudo systemctl stop mysql.service
sudo sed -i 's/bind-address/# bind-address/g' /etc/mysql/mariadb.conf.d/50-server.cnf

sudo cp -r /home/pi/mirrohr/files/* /
sudo systemctl daemon-reload
sudo systemctl start mysql.service
sudo systemctl enable raspberrypi-net-mods.service
sudo systemctl enable raspberrypi-static-net-mods.service
sudo systemctl enable mirrohr-screen.service
sudo systemctl disable dnsmasq.service

if [ ! -f /boot/dhcpcd.conf ]; then
	sudo cp /etc/dhcpcd.conf /boot/
fi

if [ ! -f /boot/wpa_supplicant.conf ]; then
	sudo cp /etc/wpa_supplicant/wpa_supplicant.conf /boot/
fi
sudo cp /etc/splash_1_right.png /etc/splash.png
sudo cp -r /home/pi/mirrohr/kernel/* /
sudo reboot
