#!/bin/bash

apache2
apache2-bin
apache2-data
apache2-utils

chromium-browser
chromium-browser-l10n
chromium-codecs-ffmpeg-extra

dnsmasq
dnsmasq-base

fbi

fontconfig
fontconfig-config
fonts-dejavu-core
fonts-droid-fallback
fonts-noto-mono

geoclue-2.0

hostapd

mariadb-client-10.1
mariadb-client-core-10.1
mariadb-common
mariadb-server
mariadb-server-10.1
mariadb-server-core-10.1
mysql-common

matchbox
matchbox-common
matchbox-desktop
matchbox-keyboard
matchbox-keyboard-im
matchbox-panel
matchbox-panel-manager
matchbox-window-manager

php-cli-prompt
php-common
php-composer-ca-bundle
php-composer-semver
php-composer-spdx-licenses
php-json-schema
php-psr-log
php-symfony-console
php-symfony-filesystem
php-symfony-finder
php-symfony-polyfill-mbstring
php-symfony-process
php7.0
php7.0-bz2
php7.0-cli
php7.0-common
php7.0-curl
php7.0-gd
php7.0-intl
php7.0-json
php7.0-mbstring
php7.0-mysql
php7.0-opcache
php7.0-readline
php7.0-soap
php7.0-xml
php7.0-zip

qrencode

x11-common
x11-utils
x11-xkb-utils
x11-xserver-utils

xfonts-base
xfonts-encodings
xfonts-utils
xinit
xkb-data
xml-core
xserver-common
xserver-xorg
xserver-xorg-core
xserver-xorg-input-all
xserver-xorg-input-libinput
xserver-xorg-input-wacom
xserver-xorg-legacy
xserver-xorg-video-all
xserver-xorg-video-amdgpu
xserver-xorg-video-ati
xserver-xorg-video-fbdev
xserver-xorg-video-nouveau
xserver-xorg-video-radeon
xserver-xorg-video-vesa


